### ISSUE TITLE
[BUG] Setting the batches variable causes an Invalid Argument error

### ISSUE THREAD

**Issue by MrHedmad** [CMA-Lab/bioTEA#5]
**Describe the bug**
On a new analysis, setting the `experimental_design > batches` variable to anything other than `None` causes a `ValueError`:
```
Traceback (most recent call last):
  File "/home/hedmad/Files/panc_dec22/env/lib/python3.10/site-packages/bioTea/docker_wrapper.py", line 292, in parse_arguments
    self.possible_args[key](value)
  File "/home/hedmad/Files/panc_dec22/env/lib/python3.10/site-packages/bioTea/docker_wrapper.py", line 231, in __call__
    raise ValueError(f"Argument check failed. Invalid argument {argument}")
ValueError: Argument check failed. Invalid argument one, two, one, two

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hedmad/Files/panc_dec22/env/lib/python3.10/site-packages/bioTea/docker_wrapper.py", line 450, in run_biotea_box
    parsed_args = interface.parse_arguments(**arguments)
  File "/home/hedmad/Files/panc_dec22/env/lib/python3.10/site-packages/bioTea/docker_wrapper.py", line 295, in parse_arguments
    raise ValueError(f"Argument check failed for key {key}: {value}")
ValueError: Argument check failed for key batches: one, two, one, two
```

**To Reproduce**
1. Create a new folder, with a virtual environment.
2. Install `bioTea`
3. Create a mock dataset with 4 random columns of data + a `probe_id` column.
4. Create a new option file with `biotea initialize`
5. Set the `batches` variable
6. Run the analysis with `biotea analyze`

**Expected behavior**
The batches should be parsed as normal.

**Desktop:**
 - OS: Windows Subsystems for Linux running Arch
 - BioTEA Version: 1.0.2
 - Docker engine version: 20.10.21
 - BioTEA container version: 1.0.2

**Comment by MrHedmad** [comment]
The direct issue is due to this line:
 https://github.com/CMA-Lab/bioTEA/blob/4e0e2624926f0ae00ff288b3efc2c5fb2de279ac/src/bioTea/bioTea/docker_wrapper.py#L361
 Instead of passing a string, the argument checker wants a list of strings.
 
 Passing in a list with just one batch string raises another error during the RankProd analysis: 
 ```
 Wed Dec  7 08:56:28 2022 [error]: Length of batches vector is not the same as the groups.
 ```
 With no traceback. It's not clear to me if the issue is in how the batches are passed (i.e. it needs a string, not a list of strings, I have to change the argument parser), or in the RankProd analysis itself (i.e. the RankProd analysis is broken, and we need to change the batches documentation).

**Comment by MrHedmad** [comment]
There seem to be a few compounding problems here: first, the `BioTeaBoxArgument` filter is wrong, a single string is valid. Second, the rankprod analysis is wrong. When setting batches, these lines:
https://github.com/CMA-Lab/bioTEA/blob/4e0e2624926f0ae00ff288b3efc2c5fb2de279ac/src/box/modules/analyze/analysis_core.R#L715-L728
cause the `batches` variable to be overridden, causing the error *just on multiple rankprod runs*. This is the error I was seeing before.
